import { sqrt, floor, ceil, round, abs, sin, cos, tan, PI, pow, min, max, random, randomInt, log, exp } from "../../std/math.js";
const x = (-7.8);
console.log(`Original: ${x}`);
console.log(`Absolute: ${abs(x)}`);
console.log(`Floor: ${floor(x)}`);
console.log(`Ceil: ${ceil(x)}`);
console.log(`Round: ${round(x)}`);
const num = 16;
console.log(`Square root of ${num}: ${sqrt(num)}`);
console.log(`2^8 = ${pow(2, 8)}`);
console.log(`e^2 = ${exp(2)}`);
console.log(`ln(10) = ${log(10)}`);
const angle = (PI() / 4);
console.log(`PI = ${PI()}`);
console.log(`sin(PI/4) = ${sin(angle)}`);
console.log(`cos(PI/4) = ${cos(angle)}`);
console.log(`tan(PI/4) = ${tan(angle)}`);
const a = 10;
const b = 25;
console.log(`min(${a}, ${b}) = ${min(a, b)}`);
console.log(`max(${a}, ${b}) = ${max(a, b)}`);
console.log(`Random float: ${random()}`);
console.log(`Random int 1-100: ${randomInt(1, 100)}`);
console.log(`Random int 1-100: ${randomInt(1, 100)}`);
const x1 = 0;
const y1 = 0;
const x2 = 3;
const y2 = 4;
const dx = (x2 - x1);
const dy = (y2 - y1);
const distance = sqrt(((dx * dx) + (dy * dy)));
console.log(`Distance from (${x1},${y1}) to (${x2},${y2}) = ${distance}`);