import { sort, sortDesc, reverse, includes, indexOf, sum, average, minVal, maxVal, unique, first, last, isEmpty, slice, concat, join, count } from "../std/array.js";
const nums = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3];
console.log(`Original: ${nums}`);
console.log(`First: ${first(nums)}`);
console.log(`Last: ${last(nums)}`);
console.log(`Is empty: ${isEmpty(nums)}`);
console.log(`Contains 5: ${includes(nums, 5)}`);
console.log(`Contains 99: ${includes(nums, 99)}`);
console.log(`Index of 4: ${indexOf(nums, 4)}`);
console.log(`Index of 99: ${indexOf(nums, 99)}`);
console.log(`Sorted asc: ${sort(nums)}`);
console.log(`Sorted desc: ${sortDesc(nums)}`);
console.log(`Original unchanged: ${nums}`);
console.log(`Reversed: ${reverse(nums)}`);
console.log(`Unique values: ${unique(nums)}`);
console.log(`Slice [2..5]: ${slice(nums, 2, 5)}`);
console.log(`Sum: ${sum(nums)}`);
console.log(`Average: ${average(nums)}`);
console.log(`Min: ${minVal(nums)}`);
console.log(`Max: ${maxVal(nums)}`);
console.log(`Count of 1: ${count(nums, 1)}`);
console.log(`Count of 5: ${count(nums, 5)}`);
const more = [7, 8, 9];
const combined = concat(nums, more);
console.log(`Combined: ${combined}`);
const words = ["hello", "world", "zz"];
console.log(`Joined: ${join(words, ", ")}`);
console.log(`Joined: ${join(words, " - ")}`);
const data = [5, 2, 8, 2, 9, 1, 5, 8];
const processed = sort(unique(data));
console.log(`Unique sorted: ${processed}`);